rules:
  indentation:
    - 1
    - size: 2
  empty-line-between-blocks:
    - 0
  no-vendor-prefixes:
    - 0
  property-sort-order:
    - 0
  single-line-per-selector:
    - 0
  no-url-domains:
    - 0
  no-url-protocols:
    - 0
  no-duplicate-properties: 
    - ignore_consecutive: true
